[package]
name = "audio-ops"
version = "1.0.0"
edition = "2021"

[dependencies]
once_cell = "1.18.0"
riff-wave = "0.1.3"

[dev-dependencies]
divan = "0.1.2"

[[bench]]
name = "benchmarks"
harness = false
