[package]
name = "usage"
version = "0.1.0"
edition = "2021"

[dependencies]
sonata-piper = { path = "../../sonata/models/piper" }
sonata-synth = { version = "0.2.0", path = "../../sonata/synth" }
ort = "2.0.0-rc.1"
